### ISSUE TITLE
composer require hyperized/hostfact does not download latest version

### ISSUE THREAD

**Issue by basepack** [hyperized/hostfact#26]
Hi,

Maybe we have to push a new version, because when you do `composer require hyperized/hostfact` you get v2.7 and this version is behind master and uses old Wefact code.

We need the `dev-master` branche for the correct code.

Maybe push a v2.8 version tag which is updated?

**Comment by hyperized** [comment]
Hi @basepack,

Thanks for the heads-up, I just pushed https://github.com/hyperized/hostfact/tree/v2.8.0
