### ISSUE TITLE
Laravel 6.0 compatibility

### ISSUE THREAD

**Issue by vdhicts** [hyperized/hostfact#30]
# Problem

When updating to Laravel 6.0, composer throws the following error:

```
- Installation request for hyperized/hostfact ^2.8 -> satisfiable by hyperized/hostfact[v2.8.0].
- Conclusion: remove laravel/framework v6.0.0
```

# Cause

The cause of this problem is by the following line in `composer.json`:

`"illuminate/support": "^5.4",`

# Solution

It looks like (haven't tested it yet) a version bump of the `illuminate/support` would be everything that's required. When I have some time, I will give it a test.

**Comment by hyperized** [comment]
@vdhicts If you have some time, could you test the merge request #31? My tests don't cover anything related to the Illuminate libs.

**Comment by vdhicts** [comment]
Yes I will!

**Comment by hyperized** [comment]
@vdhicts That should do it, it's now tagged as v2.8.1 (I still have to implement newer versions of the API)

**Comment by vdhicts** [comment]
Thank you very much for the quick reply and action! It works like a charm.
