### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by dvdheiden** [hyperized/hostfact#42]
Currently composer.json requires php ^7.2.5. For PHP 8 that won't work. 

Changing it to:

```json
"php": "^7.2.5|^8.0",
```

Would probably already solve it. Would you accept a PR for PHP 8 compatiblity?

**Comment by hyperized** [comment]
@dvdheiden Thank you, yes I absolutely would 👍🏻

**Comment by hyperized** [comment]
Tracking this PR: https://github.com/hyperized/hostfact/pull/44

**Comment by hyperized** [comment]
Closed with: https://github.com/hyperized/hostfact/releases/tag/v3.0.0
