### ISSUE TITLE
The Safe PHP package isn't required but is used by this package

### ISSUE THREAD

**Issue by dvdheiden** [hyperized/hostfact#46]
In [Api.php ](https://github.com/hyperized/hostfact/blob/05377e103750fe1a87c0f3c1fd81bca66dc7c929/src/Api/Api.php#L100), among other places, the [Safe PHP package](https://github.com/thecodingmachine/safe) is used. 

This package isn't included in the composer.json of the package which might cause an error.

**Comment by hyperized** [comment]
Great find! I don't quite understand why I never noticed this, PHPStorm resolved it just fine 🤷🏻‍♂️.
Will fix and release 3.0.1 soon.

**Comment by dvdheiden** [comment]
Thank you!
